### ISSUE TITLE
Suggestion: only show A-Z marks on respective file

### ISSUE THREAD

**Issue by awvalenti** [yaocccc/vim-showmarks#2]
Currently, A-Z marks are shown on every file. I believe they would be more useful if shown only on file which actually has the mark on it.

**Comment by yaocccc** [comment]
I have made a simple repair. I can't confirm whether it works, keep watching.

**Comment by awvalenti** [comment]
Tested here and it's working! Thank you!

**Comment by awvalenti** [comment]
Hey yaocccc, unfortunately it's still not fully working. On Windows, only when I open a second file the marks become OK. On Mac, apparently even in that situation the uppercase marks keep showing on different files.

**Comment by yaocccc** [comment]
wait me some time to fix it, my archlinux is broken

**Comment by yaocccc** [comment]
> Hey yaocccc, unfortunately it's still not fully working. On Windows, only when I open a second file the marks become OK. On Mac, apparently even in that situation the uppercase marks keep showing on different files.

fixed

**Comment by awvalenti** [comment]
Fixed, yeah!!
