### ISSUE TITLE
Error while loading plugin on Linux

### ISSUE THREAD

**Issue by awvalenti** [yaocccc/vim-showmarks#4]
```
Error detected when processing function <SNR>71_showMarks[4]..<SNR>71_getMarks:
line    1:
E117: Unknown function: getmarklist
line    2:
E121: Undefined variable: marks
E116: Invalid arguements for function filter(marks, 'v:val.mark[1] =~# s:enabled_marks')
line    4:
E121: Undefined variable: marks
```

They appeared when I installed the plugin on Linux for the first time and also when loading a file, both in terminal and GVim.

Not sure if it also happens on other platforms, I can check it if you want.

**Comment by awvalenti** [comment]
They appeared too when I installed the plugin on Linux for the first time.

Will try using a previous version for now.

**Comment by yaocccc** [comment]
please update version and check it

**Comment by awvalenti** [comment]
That error is fixed!
When I try to update all plugins, it still shows some error from `showmarks`, but that doesn't prevent the update from working, so no big deal.
Thanks!
