### ISSUE TITLE
noremap <unique> results in error when updating plugin

### ISSUE THREAD

**Issue by awvalenti** [yaocccc/vim-showmarks#5]
File plugin/marks.vim:42 has this content:
```vim
noremap <unique> <script> \sm m
```

When I run `:PlugUpdate` from vim-plug to update all plugins, I get an error from that line because it tries to redo mapping:
![vim-erro-plug-update](https://github.com/yaocccc/vim-showmarks/assets/834921/7cc1283a-8640-48a9-959f-b0aab9521301) (in Portuguese)

Is that `<unique>` part really necessary?

**Comment by yaocccc** [comment]
> File plugin/marks.vim:42 has this content:
> 
> ```viml
> noremap <unique> <script> \sm m
> ```
> 
> When I run `:PlugUpdate` from vim-plug to update all plugins, I get an error from that line because it tries to redo mapping: ![vim-erro-plug-update](https://private-user-images.githubusercontent.com/834921/304898748-7cc1283a-8640-48a9-959f-b0aab9521301.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MzgwNTYsIm5iZiI6MTcwODQzNzc1NiwicGF0aCI6Ii84MzQ5MjEvMzA0ODk4NzQ4LTdjYzEyODNhLTg2NDAtNDhhOS05NTlmLWIwYWFiOTUyMTMwMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxNDAyMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTA2NzY3MGI3OWIwOTBlMzcyYmViZDJmYzM3YTdhZDg5OWY2NTNlYjdkYWIxNGRlZjEwYTlhMTlkMmFlMWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9GmgneWWfVgXP5IaDax9X41duVSSVEKL5pKeNj1lu5E) (in Portuguese)
> 
> Is that `<unique>` part really necessary?

Yep, I try remove <unique>.
You are right, I's unnecessary.
